plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-sorbet

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  Exclude:
    - "bin/*"
    - "db/*schema.rb"
    - 'spec/dummy/db/schema.rb'
    - 'spec/dummy/lib/permission.rb'
    - "vendor/**/*"

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^# [^\n]+'

Layout/HashAlignment:
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: table

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

# Causes issues with the typical way to define Rails scopes
Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "db/migrate/*.rb"

Metrics/CyclomaticComplexity:
  Max: 25
  Exclude:
    - "db/migrate/*.rb"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ModuleLength:
  Max: 200
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/BlockLength:
  Exclude:
    - "app/**/concerns/**/*.rb"
    - "config/environments/*.rb"
    - "config/routes.rb"
    - "db/migrate/*.rb"
    - "lib/tasks/**/*.rake"
    - "spec/**/*"
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ClassLength:
  Max: 200
  Exclude:
    - "db/migrate/*.rb"
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Naming/BlockForwarding:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - as
    - at
    - by
    - cc
    - db
    - id
    - if
    - in
    - io
    - ip
    - mu
    - on
    - os
    - to

Naming/PredicatePrefix:
  NamePrefix:
    - is_
    - have_
  ForbiddenPrefixes:
    - is_
    - have_

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Rails/DynamicFindBy:
  Enabled: false

RSpec:
  Language:
    Includes:
      Examples:
        - succeed
        - failed

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/NestedGroups:
  Max: 5

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpecRails/NegationBeValid:
  EnforcedStyle: be_invalid

Sorbet/ConstantsFromStrings:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
