# typed: strict
# frozen_string_literal: true

require 'phalanx/generator/dsl'

module Phalanx
  class Generator
    extend T::Sig

    MAGIC_COMMENT = <<~MAGIC_COMMENT
      typed: strict
      frozen_string_literal: true
    MAGIC_COMMENT

    HEADER = <<~HEADER
      GENERATED FILE - DO NOT MODIFY

      This file was generated by Phalanx.
      Use `rails phalanx:generate` to regenerate this file.
    HEADER

    sig { params(permission_groups: T::Array[Parser::PermissionGroup], output_class_name: String, output_path: Pathname).void }
    def initialize(permission_groups, output_class_name:, output_path:)
      @permission_groups = permission_groups
      @output_class_name = output_class_name
      @output_path = output_path
      @dsl = T.let(DSL.new, DSL)
    end

    sig { returns(T::Boolean) }
    def stale?
      # Early check if file is missing
      return true unless File.exist?(@output_path)

      file = Tempfile.new(['permission', '.rb'])
      generate_permissions_class
      file.write(@dsl.generate)
      file.flush

      !FileUtils.identical?(@output_path, T.must(file.path))
    ensure
      file&.close
    end

    sig { void }
    def generate
      file = File.open(@output_path, 'w')
      generate_permissions_class
      file.write(@dsl.generate)
    ensure
      file&.close
    end

  private

    sig { void }
    def generate_permissions_class
      @dsl.comment(MAGIC_COMMENT)
      @dsl.newline
      @dsl.comment(HEADER)
      @dsl.class(@output_class_name, superclass: 'T::Enum') do |dsl|
        dsl.include('Phalanx::Permission')
        dsl.enums do
          @permission_groups.each do |permission_group|
            generate_enums_values_for_permission_group(dsl, permission_group)
          end
        end
      end
    end

    sig { params(dsl: DSL, permission_group: Parser::PermissionGroup).returns(DSL) }
    def generate_enums_values_for_permission_group(dsl, permission_group)
      dsl.comment("Permissions for #{permission_group.subject}")
      dsl.newline
      permission_group.permissions.each do |permission|
        dsl.comment(T.must(permission.description).squish) if permission.description.present?
        dsl.enum(
          permission.constant_name, {
            id: permission.id,
            subject: permission_group.subject,
            name: permission.name,
            scope: permission.scope,
            description: permission.description,
            implies: permission.implies,
          }
        )
      end
      dsl.newline
    end
  end
end
