# typed: strict
# frozen_string_literal: true

# GENERATED FILE - DO NOT MODIFY
# 
# This file was generated by Phalanx.
# Use `rails phalanx:generate` to regenerate this file.
class Permission < T::Enum
  include Phalanx::Permission
  enums do
    # Permissions for User

    # Allows the authenticated user to see their own account
    USERS_SHOW_OWN = new(
      :id => "users.show.own",
      :group_name => "User",
      :name => "Show own user",
      :description => "Allows the authenticated user to see their own account",
      :depends_on => nil,
    )
    # Allows the authenticated user to update their own account
    USERS_UPDATE_OWN = new(
      :id => "users.update.own",
      :group_name => "User",
      :name => "Update own user",
      :description => "Allows the authenticated user to update their own account",
      :depends_on => "users.show.own",
    )
    # Allows the authenticated user to delete their own account
    USERS_DESTROY_OWN = new(
      :id => "users.destroy.own",
      :group_name => "User",
      :name => "Destroy own user",
      :description => "Allows the authenticated user to delete their own account",
      :depends_on => "users.update.own",
    )
    # Allows the authenticated user to see any user's account
    USERS_SHOW_ANY = new(
      :id => "users.show.any",
      :group_name => "User",
      :name => "Show any user",
      :description => "Allows the authenticated user to see any user's account",
      :depends_on => "users.show.own",
    )
    # Allows the authenticated user to update any user's account
    USERS_UPDATE_ANY = new(
      :id => "users.update.any",
      :group_name => "User",
      :name => "Update any user",
      :description => "Allows the authenticated user to update any user's account",
      :depends_on => "users.show.any",
    )
    # Allows the authenticated user to delete any user's account
    USERS_DESTROY_ANY = new(
      :id => "users.destroy.any",
      :group_name => "User",
      :name => "Destroy any user",
      :description => "Allows the authenticated user to delete any user's account",
      :depends_on => "users.update.any",
    )

  end
end
