# typed: strict
# frozen_string_literal: true

# GENERATED FILE - DO NOT MODIFY
# 
# This file was generated by Phalanx.
# Use `rails phalanx:generate` to regenerate this file.
class Permission < T::Enum
  include Phalanx::Permission
  enums do
    # Permissions for User

    # Allows the authenticated user to see their own account
    USERS_SHOW_OWN = new(
      :id => "users.show.own",
      :subject => "User",
      :name => "Show own user",
      :scope => "User",
      :description => "Allows the authenticated user to see their own account",
      :implies => [],
    )
    # Allows the authenticated user to update their own account
    USERS_UPDATE_OWN = new(
      :id => "users.update.own",
      :subject => "User",
      :name => "Update own user",
      :scope => "User",
      :description => "Allows the authenticated user to update their own account",
      :implies => ["users.show.own"],
    )
    # Allows the authenticated user to delete their own account
    USERS_DESTROY_OWN = new(
      :id => "users.destroy.own",
      :subject => "User",
      :name => "Destroy own user",
      :scope => "User",
      :description => "Allows the authenticated user to delete their own account",
      :implies => ["users.update.own"],
    )
    # Allows the authenticated user to see any user's account
    USERS_SHOW_ANY = new(
      :id => "users.show.any",
      :subject => "User",
      :name => "Show any user",
      :scope => "User",
      :description => "Allows the authenticated user to see any user's account",
      :implies => ["users.show.own"],
    )
    # Allows the authenticated user to update any user's account
    USERS_UPDATE_ANY = new(
      :id => "users.update.any",
      :subject => "User",
      :name => "Update any user",
      :scope => "User",
      :description => "Allows the authenticated user to update any user's account",
      :implies => ["users.show.any", "users.update.own"],
    )
    # Allows the authenticated user to delete any user's account
    USERS_DESTROY_ANY = new(
      :id => "users.destroy.any",
      :subject => "User",
      :name => "Destroy any user",
      :scope => "User",
      :description => "Allows the authenticated user to delete any user's account",
      :implies => ["users.update.any", "users.destroy.own"],
    )

  end
end
